### ISSUE TITLE
Generalization of this framework

### ISSUE THREAD

**Issue by lalas** [wleepang/DesktopDeployR#1]
Hello

First of all, let me congratulate you on putting the different pieces together, and make it easier to deploy R/Shiny to non R-User. This is more of a question rather than an issue:

Is it possible to generalize this framework to work on other OS (eg OSX and Ubuntu)? Does R-portable exist for non-windows os?

Cheers

**Comment by wleepang** [comment]
@lalas 
Thanks!

It would be great to generalize the framework to be cross-platform.  Unfortunately, at this time R-Portable only exists for Windows machines.

I haven't done much digging (yet) into what it would take to make R portable on Linux or OS X or if a workable solution already exists. The first thing that comes to mind would be to use a Docker container for R - i.e. https://github.com/rocker-org/rocker.

**Comment by mayeulk** [comment]
I'm happy to help and test (Ubuntu 16.04, 64 bits; Windows 10; maybe MacOS). I created a linux R packaging script for Windows: [https://github.com/mayeulk/R_Tinn-R_Portables] You might find some ideas there.
