### ISSUE TITLE
allow installing R package from non-CRAN source

### ISSUE THREAD

**Issue by mayeulk** [wleepang/DesktopDeployR#11]
https://github.com/wleepang/DesktopDeployR/blob/8062916449b1c685706835e85f40d48e78f9ee45/dist/script/R/run.R#L20

For instance allow something like:
`devtools::install_github(repo = "garthtarr/pairsD3")`

**Comment by mayeulk** [comment]
Also, summarized (and edited) from [https://coderwall.com/p/vuguzq/installing-r-packages-from-cran-bioconductor-omegahat-github]

- [ ] Offline (already downloaded package)
Could be usefull e.g. for users with no or slow internet connection, or unpublished packages

`install.packages("/home/trendwise/Downloads/R packages/RSPython_0.7-1.tar.gz",repos=NULL,lib=.libPaths()[1])`

- [ ] Online R script (which in coderwall.com example allows to install other packages)

```
# installing biocLite
# required for downloading & installing Bioconductor packages
source("http://bioconductor.org/biocLite.R")
biocLite() # installs automatically 'Biobase' 'IRanges' 'AnnotationDbi' ‘BiocGenerics’ ‘RSQLite’
biocLite(c("GenomicFeatures", "AnnotationDbi"))
```


Note: does it make sense to allow to execute some code in the DesktopDeployR if some conditions is  met, for eg installing something?

- [ ] Omegahat
```
install.packages("RCurl", repos = "http://www.omegahat.org/R")
  #  For some packages, there are binaries for Windows.
  # For most others, you will need to specify to download the source package
install.packages(packageName, repos = "http://www.omegahat.org/R", type = "source")
```

- [ ] Github

```
install.packages("devtools")
library(devtools)  # see [https://stackoverflow.com/questions/5595512/what-is-the-difference-between-require-and-library]
 install_github("rplos", "rOpenSci")
```

- [ ] RForge
```
install.packages("audio",repos="http://rforge.net")
install.packages('knitr', repos = c('http://rforge.net', 'http://cran.rstudio.org'),type = 'source')
```

**Comment by wleepang** [comment]
These are great ideas.  Package "ensure"-ing could potentially incorporate all of these options and handled by a small DSL in the packages.txt file.
