### ISSUE TITLE
Allow installing a particular package version

### ISSUE THREAD

**Issue by mayeulk** [wleepang/DesktopDeployR#12]
https://github.com/wleepang/DesktopDeployR/blob/8062916449b1c685706835e85f40d48e78f9ee45/dist/script/R/run.R#L20

For instance:
```
devtools::install_github(repo = "garthtarr/pairsD3",
                         ref = "69289763291e0fd95ac9c369bc83c23d1121eaea")
```

instead of
`
devtools::install_github(repo = "garthtarr/pairsD3")`
This is helpful for packages changing at a fast pace, and to ensure robustness over changes, and reproducibility of scientific computations.
Would it be helpful to use packrat?
[packrat](https://www.rstudio.com/resources/webinars/managing-package-dependencies-in-r-with-packrat/)

**Comment by wleepang** [comment]
I like pointing to a specific commit as a means for version pinning.  I haven't had much success with packrat on its own (i.e. in my standard analysis workflow in RStudio).  I personally wish there was something akin to Python's `pip` in R.

**Comment by wleepang** [comment]
Not a priority at the moment.
