### ISSUE TITLE
Have to close R with Task Manager to Reopen App

### ISSUE THREAD

**Issue by py9mrg** [wleepang/DesktopDeployR#13]
Hello,

Maybe I'm doing something stupid, but every time I run the app and then close the browser window - I cannot reopen the app. Batch file runs but nothing happens. I have found that I can get it to reopen only if I go to Task Manager and manually force the Rscript.exe process to stop. Am I doing something stupid!?

Thanks.

**Comment by py9mrg** [comment]
Oh, hang on - just found the discussion about this in the closed issues. The repackaging doesn't work for me unfortunately - and I am using Chrome. Unable to change this as it's forced as the default by the company - so if I'm going to distribute apps, it needs to be able to work with Chrome. An error file is generated, but doesn't appear to show any:

[error.log](https://github.com/wleepang/DesktopDeployR/files/1527031/error.log)

**Comment by wleepang** [comment]
Did you register a handler for `session$onSessionEnded` with a call to
shiny::stopApp() in your `server.R` file?

**Comment by py9mrg** [comment]
I hadn't until I found the closed issue. Weirdly, if I include that in the same manner, then I get a weird ghosted out browser window - but all the widgets work "underneath" it. If I don't include it then the window looks normal. Either way, the reopen problem exists with both. (I'm using the shiny ui and server files from their widgets example)

I'm thinking this might be a Chrome specific issue - but I'm far from a shiny expert (made 1 app a year ago!), or github, so I'm trying to learn both as I go along. I'm uploading my ui and server file (just changed to a .
[server.txt](https://github.com/wleepang/DesktopDeployR/files/1527278/server.txt)
[ui.txt](https://github.com/wleepang/DesktopDeployR/files/1527279/ui.txt)

txt so it lets me) - and I've got a branch "FirstTrial" if you want to look at the rest on my profile. No worries if you can't sort it - thanks for looking anyway.

**Comment by py9mrg** [comment]
Sorry - I am being an idiot. When I added the stopApp() etc commands, I forgot to include session as an argument to the shinyServer function. Works fine now.
