### ISSUE TITLE
GPL virality

### ISSUE THREAD

**Issue by alamit** [wleepang/DesktopDeployR#14]
I just opened this [issue](https://github.com/ficonsulting/RInno/issues/46) on `RInno`package. 

I think the same issue applies to `DesktopDeployR`.

What do you think?

**Comment by wleepang** [comment]
I'm not a legal expert, and if distributing software within a corporate environment you should verify any use of OSS against policies that are in place.

I think @DripDrop12 gave a sufficient answer in the issue thread for `RInno` and the same logic applies to `DesktopDeployR`.
