### ISSUE TITLE
run.js

### ISSUE THREAD

**Issue by wtf13** [wleepang/DesktopDeployR#16]
Hello Lee Pang

Thank you so much for creating this framework!
I managed to deploy it successfully on my Windows desktop. However, when I transferred the program files to a secured environment, the program stops after it reaches the file in dist/script/wsf/js/run.js. 

The following steps were logged: 
.bat file was allowed to run
dist/script/wsf/run.wsf was allowed to run
dist/script/wsf/js/json2.js was allowed to run
dist/script/wsf/js/json.minify.js was allowed to run
dist/script/wsf/js/run.js was allowed to run

The process terminates afterwards. 
Wanted to check if the run.js file requires any additional configurations or external dependencies/special settings? 

Cheers~

**Comment by wtf13** [comment]
@wleepang Thanks so much for your reply!  

I was checking with some of my coworkers, it seems that portable apps were blocked from our operating system. I'm trying to modify your framework by working with R instead of R-Portable packaged within the folders. Any advice on this?

**Comment by wleepang** [comment]
@wtf13 - you need to escape the "\" characters, so the option in `config.cfg` should be:

```
"r_bindir": "C:\\Program Files\\R\\R-3.3.2\\bin"
```

**Comment by wtf13** [comment]
Thanks leepang! That was exactly what I did earlier, just forgot to append my code as a chunk earlier on. 
`"r_bindir": "C:\\Program Files\\R\\R-3.3.2\\bin"`

I'm still getting the following message however: Code 80070002: The system cannot find the file specified. 

When i replaced R portable with the system installed R in the app framework within the \dist folder, it seems to work with the following in config.cfg. 

"r_bindir": "dist\\R\\R-3.4.2\\bin"

Was wondering if you have any ideas why this is happening?

**Comment by wleepang** [comment]
@wtf13 - After some testing, I found that paths with spaces weren't being handled correctly, causing the error you encountered.   I just merged in some updates that should address this issue, and added some additional flexibility in specifying the R executable used.

**Comment by wtf13** [comment]
@wleepang thanks a lot for resolving the issue! 
Managed to run it successfully from my desktop :) 

However, when I copied the entire application folder to 'Program Files" in the C: drive, the program does not launch from the new path. After the windows command prompt appears, the 'loading packages' pop-up does not show up. Any advice on why this is happening?

**Comment by wleepang** [comment]
@wtf13 - did you pre-`ensure` the package dependencies for your application prior to moving it (i.e. did you create the app library on your development desktop)?

It sounds like there might be some access permissions restrictions for the R interpreter.
Does it work from another location accessible to users?

**Comment by wleepang** [comment]
Closing as this is more than 1yr old. Feel free to reopen if still an issue.
