### ISSUE TITLE
Basics - Getting it to work

### ISSUE THREAD

**Issue by EliSucksatR** [wleepang/DesktopDeployR#18]
Hi,

I'm really bad at all this stuff so please bare with me. I've downloaded the repository and tried to run the app using the script supplied in the framework but I get an error....

Error: R executable not found:
C:\Programme Files\R\R-3.3.2\bin\Rscript.exe

I downloaded R portable and saved in the right place. Do I need to edit the 'r_exec' within the config.cfg?

Any help would be really appreciated

**Comment by EliSucksatR** [comment]
I've worked it out. For anyone with same issue you need to change config file R_exec path to r-portable

**Comment by wleepang** [comment]
@EliSucksatR - Glad you were able to get it working.

FYI, the built-in default should point to the R-portable binary path.  To use the default, simply omit the `r_exec` option in the config file.
