### ISSUE TITLE
checkpoint?

### ISSUE THREAD

**Issue by r2evans** [wleepang/DesktopDeployR#2]
Great idea, I'm definitely going to play with it. (Unfortunately, most of my clients trust me to do the R ... they just want "answers"!)

Thought: when an app is deployed to the client, there is an assumption that things work as they did when the app was deployed. Unfortunately, if you automatically update installed packages, this might break things.

What do you think about [`checkpoint`](https://cran.r-project.org/web/packages/checkpoint/index.html)-like dependency handling, either _always_ or some mechanism for opting in? (For instance, packages that make significant changes to the function names, defaults, or API often increment the package's major number; a simple upgrade will see a higher number and update regardless of the untested ramifications this will have on the other deployed packages.)

As much as I don't use `checkpoint` for my normal use, it's because I control my own environment. When I give it to clients, I can only assume that they will keep using it well beyond the timeline I foresaw (or agreed), by which time some dependencies will have made huge changes to their API.

**Comment by wleepang** [comment]
I like the idea of using `checkpoint` as it's the closest method to freezing r package dependencies to specific versions for deployment I've encountered. I've played with it a little, and so far I like how it works. It shouldn't be too hard to add an opt in. Thanks for the suggestion.
