### ISSUE TITLE
Use pre-installed packages

### ISSUE THREAD

**Issue by aephidayatuloh** [wleepang/DesktopDeployR#20]
I've searched about this topic but couldn't find the answer. Is it possible to this framework use the pre-installed packages (i.e. on C:\Users\aephidayatuloh\Documents\R\win-library\3.5) instead of app/library? So the initialization process could be lighter.

Thanks.

**Comment by aephidayatuloh** [comment]
@wleepang Thanks for your response.

Please correct me if I am wrong. When I first run the framework by double-clicking appname.bat, the framework will see whether the packages (at least jsonlite) needed are installed in the app/library folder. If there are no packages available on it (because first time) so the framework will install the required packages into the app/library folder.

What I'm thinking is the framework doesn't need to look into the app/library folder, but it looks into C: \user\aephidayatuloh\Documents\R\win-library\3.5 when I run the framework because I already installed the jsonlite package on it.

This will be very useful when I have lots of frameworks and only need to use centralized Rscript.exe and packages. Is there any options to do that?

I hope my question is clear enough.

Thanks

**Comment by aephidayatuloh** [comment]
Hi, I've found out how to solved my own problem. 

If I want to use the pre-installed packages (i.e C: \user\aephidayatuloh\Documents\R\win-library\3.5) so the framework doesn't need to create app/library and install required packages (jsonlite) for the very first time run the appname.bat file, I changed the /dist/script/R/run.R file.

I changed form this
```
appwd = getwd()
applibpath = file.path(appwd, 'app', 'library')

# create app/library if it doesn't exist (e.g. first run)
if(!dir.exists(applibpath)) {
  dir.create(applibpath)
}

.libPaths(c(applibpath, .Library))
```
to this
```
appwd = getwd()
applibpath = file.path(appwd, 'app', 'library')
centralibpath <- "C:/Users/aephidayatuloh/Documents/R/win-library/3.5"

# create app/library if it doesn't exist (e.g. first run)
if (!dir.exists(centralibpath)) {
  if(!dir.exists(applibpath)) {
    dir.create(applibpath)
    .libPaths(c(applibpath, .Library))
  }
} else {
  .libPaths(c(centralibpath, .Library))
}
```

Thank you @wleepang, I figured out this after I re-read your answer and find this file. This is great framework.

**Comment by wleepang** [comment]
Glad that you were able to find a solution. Rather than hard coding the path, if suggest making it a configurable option and have both paths available for finding libraries. That way if your organization has a standard R installation, you could leverage packages therein as well as ones that only ship with your application.
