### ISSUE TITLE
How to make global.R work

### ISSUE THREAD

**Issue by NashVio** [wleepang/DesktopDeployR#21]
Hello everybody,

I have trouble using global.R.

I defined some constants there and saved the file as proposed in the application structure in app/shiny/global.R

But when starting the app, the defined constants are not accessible.

Do I have to tell shiny to load global.R?

**Comment by wleepang** [comment]
I just tested this with the example app in the repo, and everything works as expected.  Can you provided details of your environment - e.g. versions of `R` and `shiny`?

**Comment by NashVio** [comment]
My example is running fine otherwise. It's just that global.R is not considered.  In the global.R file I just load same data like data <- read.table('example.txt'). But when something in the app tries to access this data it seems not to be available.

> sessionInfo(package=NULL)
> R version 3.5.3 (2019-03-11)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1


> packageVersion('Shiny')
> ‘1.3.2’

**Comment by wleepang** [comment]
Could not replicate. Closing since this is over 1yr old. Feel free to reopen if still an issue.
