### ISSUE TITLE
Packing the shiny app before DesktopDeploying it

### ISSUE THREAD

**Issue by gdgaston** [wleepang/DesktopDeployR#22]
hello everyone,

First, congratulations for this great idea!
I successfully ran the example in this repository that launched my default browser and rendered the app.

Now, I would like to packaging the shiny files before desktopdeploying it. For that, I included a *launchApp* function when packaging

    launchApp <- function(){
      shiny::shinyApp(ui, server)
    }

This package, let's say, MyPackage, could be attached and the function *launcApp()* can launch the app manually in the R terminal

Then I manually add this package into the app/library and changed the app.R function as
    MyPackage::launchApp()

Once the appname.bat is launched, the browser opened and closed automatically. 
What did I miss? Grateful if you could guide me on how to packaging first the shiny files before desktopdeploying it. Thank you

**Comment by wleepang** [comment]
Suggest checking the log file for any errors.

**Comment by wleepang** [comment]
Closing as this is over 1yr old. Feel free to reopen if still an issue.
