### ISSUE TITLE
Encrypting server file

### ISSUE THREAD

**Issue by balintba** [wleepang/DesktopDeployR#25]
Hello,

this is not really an issue, more of a question. Do you see a way to encrypt the server.r file in order to protect the source code?
I want to deploy an application by the client, however I do not want them to be able to see the source file. Your comments are welcomed

Many thanks!

**Comment by wleepang** [comment]
You could create a binary package for your app that is installed in the deployed app library.  Note this only obfuscates the code.  Anyone sufficiently determined and knowledgeable about how R works would still be able to access the code.
