### ISSUE TITLE
Unable to reopen app after first run

### ISSUE THREAD

**Issue by parachutedream-s** [wleepang/DesktopDeployR#26]
Hi there, 

Every time I run the application and then exit from my web browser, I am unable to re-open it without manually shutting down the "R for Windows front-end" background process in my Task Manager. 

Is there a way to ensure that the application stops after the browser is closed?

Thanks

**Comment by wleepang** [comment]
Your app needs to register an `onSessionEnded` handler like so:

```r
shinyServer(function(input, output, session){
    ...
    session$onSessionEnded(function() {
        stopApp()
    })
    ...
})
```
