### ISSUE TITLE
UNC paths are not supported

### ISSUE THREAD

**Issue by zhangjunjiang** [wleepang/DesktopDeployR#28]
Thank you so much to share this to us.
This is a problem I'm facing now.
I want to store my shiny app  in a shared file system  where my friends can use directly without downloading it. The app work fine locally. 
But when I double click it ,an error show up: **UNC paths are not supported.  Defaulting to Windows directory**

Best regards,
Thanks

**Comment by wleepang** [comment]
Rather than using the UNC path directly, can your users map a drive letter to the network share?

**Comment by zhangjunjiang** [comment]
> Rather than using the UNC path directly, can your users map a drive letter to the network share?

sorry, I don't quite understand that, but it seems we have already have a driver letter for that ( R:// ),but this error shows  again.
What's wrong with that?

**Comment by wleepang** [comment]
Is the app library fully installed in the network share?

It seems this error pops up when trying to install packages to a remote location.
https://support.rstudio.com/hc/en-us/articles/203775903-Fixing-startup-error-where-manipulate-and-rstudio-packages-will-not-install-with-networked-drives

**Comment by zhangjunjiang** [comment]
> Is the app library fully installed in the network share?
> 
> It seems this error pops up when trying to install packages to a remote location.
> https://support.rstudio.com/hc/en-us/articles/203775903-Fixing-startup-error-where-manipulate-and-rstudio-packages-will-not-install-with-networked-drives

I have pre-install all the needed package. the I uploaded in the R:/ dir. the uploaded app I test locally, it works fine.
AND I finally  find a way to make it work.
If I click "my computer" > "R:/" > "dir i use" , the app work fine.
But if I click the spin of the whole dir  i use.  the error will pop up.
Don't know what's going on. Can you fix it?

**Comment by wleepang** [comment]
> If I click "my computer" > "R:/" > "dir i use" , the app work fine.
> But if I click the spin of the whole dir i use. the error will pop up.

Sorry, I'm not understanding what you are doing different in these two cases. Can you clarify?

**Comment by zhangjunjiang** [comment]
This question is solved by creating a short cut to the .bat file,when it works. 
the short cut can work perfectly.
