### ISSUE TITLE
Logging fails when changing config.cfg

### ISSUE THREAD

**Issue by dcaseykc** [wleepang/DesktopDeployR#29]
When I change line 42 in `config.cfg` from:

`"home": "C:\\Program Files\\R\\R-3.5.2\\bin",`
![r352](https://user-images.githubusercontent.com/49567617/85910434-9a201e00-b7d3-11ea-99b7-679ed30ceb19.PNG)

to `"dist\\R-Portable\\App\\R-Portable\\bin\\"` (running R 4.0) ![rport4](https://user-images.githubusercontent.com/49567617/85910432-99878780-b7d3-11ea-8ed1-39aef9e560e8.PNG)

or `"home": "C:\\Program Files\\R\\R-4.0.0\\bin",`![r40](https://user-images.githubusercontent.com/49567617/85910435-9a201e00-b7d3-11ea-87e5-4a17fed18d14.PNG)
the logging process seems to no longer work. For reference, I've provided some screenshots of the dialog box when I added `WScript.Echo(strCommand)` to the end of `run.js`.

Instead, it seems that the `"1>", Outfile, "2>&1"` bits are being passed as additional arguments (e.g. accessible via `commandArgs()`) to `run.R` as opposed to being treated as a way to pipe stderr and stdout to log/error.log as the defaults seemingly should do.

This reeks of something being dumb and unreproducible with my setup, but I figured I'd submit an issue in case you had any suggestions. My setup aside, this repo is extremely interesting and useful. Thank you for making it public.

**Comment by wleepang** [comment]
Is your app launched at all?

Testing this today, apps launch with R-portable 3.6.3, but not with R-portable 4.0.0. Similarly, it things with R-3.6.3, but not R-4.0.2. When the apps do launch, logging is captured appropriately.

It seems the R-4.x version has broken this method of launching apps somehow.

**Comment by dcaseykc** [comment]
The app launches just fine. It seems the only bit that is grumpy is the logging. Are there any other diagnostics I can provide?

**Comment by wleepang** [comment]
My experience might be a `shiny` package compatibility issue. Let me upgrade the library and look again.

**Comment by jsavn** [comment]
I'm experiencing the same issue with R 4.0.2. The app launches fine but doesn't log. FWIW I don't understand how the log parameter is passed to the script - is it an argument to `Rscript.exe` or are we piping output to the outfile?

**Comment by jsavn** [comment]
FWIW, using two log locations, e.g. `var strCommand     = [enquote(Rexe), Ropts, enquote(RScriptFile), "1>", Outfile, "2>", Errorfile].join(" ");` doesn't work either.

**Comment by jsavn** [comment]
Just tested with R-Portable version 3.6.3 and it works fine!

**Comment by wleepang** [comment]
I've pushed an update that addresses the logging issue as far as I can tell.

**Comment by dcaseykc** [comment]
Hi @wleepang: The log file lives! Thanks for looking into this.

**Comment by jsavinc** [comment]
Yep, works for me also :) Thanks!

**Comment by wleepang** [comment]
Excellent! Thanks for verifying the fix
