### ISSUE TITLE
Issue running vbs.run

### ISSUE THREAD

**Issue by ivonavoroneckaja** [wleepang/DesktopDeployR#3]
Hi Lee,

first of all thank you so much for coming up with this great idea! I am a statistics student and I have created an app in R Shiny, went through all the steps described as  per http://oddhypothesis.blogspot.com/2014/04/deploying-self-contained-r-apps-to.html and encounter the following issue: chrome portable does open, my app runs fine and I can use it, however a new file is created each time I press on vbs.run, it is named as some number i.e. 0.3928118 opening it in notepad  yields the following:

> proc.time()
>    user  system elapsed 
>    3.55    0.26    9.48 

However, in my code I do not use proc.time() function anywhere. When I try to delete the file - I cant do it unless I restart my pc. The error says : "The action can't be completed because  the file is open in Google Chrome Portable". My run.vbs file looks like:

> Randomize
> CreateObject("Wscript.Shell").Run "R-Portable\App\R-Portable\bin\R.exe CMD BATCH --vanilla --slave runShinyApp.R" & " " & RND & " ", 0, False

My runShinyApp.R looks like:

> require(shiny,quietly = TRUE, warn.conflicts = FALSE)
> require(shinyjs,quietly = TRUE, warn.conflicts = FALSE)
> .libPaths("./R-Portable/App/R-Portable/library")
> browser.path = file.path(getwd(),"GoogleChromePortable/GoogleChromePortable.exe")
> options(browser = browser.path)
> shiny::runApp("./Shiny/",port=8888,launch.browser= TRUE,quiet=TRUE)

Note: I added lines 1 and 2 to runShinyApp.R because in that strange file I would also get Laoding shiny...... note etc and this has removed them. 

I would be very grateful if you could give me a hand with this as I have tried everything and spent weeks trying to make it work and I have no idea what is going wrong here...

**Comment by wleepang** [comment]
I suggest also reading the following post:
http://oddhypothesis.blogspot.com/2016/04/desktop-deployr.html

which was an update to the one you referenced.  In a nutshell, I refactored the framework such that:
- Chrome portable is no longer used in favor of system installed browsers
- Launch scripts (e.g. run.js, etc ...) are generic to the type of R application being deployed and do not need to be explicitly edited.
- The framework initializes a private library for the application - i.e. there is no longer a need to install application package dependencies into R-Portable.

**Comment by ivonavoroneckaja** [comment]
Thank you for your reply. I am a statistics student and hence not familiar with programming other than R. Is there a step by step blog post available on the new framework? Something like the original post would be extremely helpful (i.e. create this copy paste that etc.).

**Comment by ivonavoroneckaja** [comment]
I followed the new framework and now I have:
Application layout:
>AppNewMethod
>>.\app
  >>>.\library
  >>>.\shiny
        >>>>.\server.R
        >>>>.\ui.R
        >>>>.\www
            >>>>>.\bootstrap.css
  >>>.\app.R
  >>>.\config.cfg 
  >>>.\packages.txt
>>.\dist
  >>>.\R-Portable
  >>>.\script
       >>>>.\R
            >>>>>.\run.R
       >>>>.\wsf
           >>>>>.\js
              >>>>>>.\JSON.minify.js
              >>>>>>.\json2.js
              >>>>>>.\run.js
           >>>>>.\run.wsf
>>.\appname.bat

I have made the following changes:

**app.R**
```
# app launching code, e.g.:
runApp("./app/shiny/", launch.browser=TRUE)
```

**packages.txt**
```

# Primary package dependencies for the application that are loaded during
# startup.
#
# If not available, they will be installed into app/library.  Custom source
# packages need to be installed manually.

# bare miniminum: configurations are stored in json format
jsonlite

# if deploying shiny based applications:
shiny
shinyjs
markdown
scales
```

Pressing **appname.bat** does not yield anything ( a black window pops out and closes immediately) 

Do you have any thoughts on what might have went wrong?

**Comment by ivonavoroneckaja** [comment]
**Update**

the app does launch, however I get the same problem as with previous framework. A new folder _log_ is created with _error.log_:

```
library paths:
... C:/Users/VoronecI/Desktop/New folder/app/library
... C:/Users/VoronecI/Desktop/New folder/dist/R-Portable/App/R-Portable/library
working path:
... C:/Users/VoronecI/Desktop/New folder
Loading required package: methods
ensuring packages: jsonlite, shiny, shinyjs, markdown, scales, DT

Attaching package: 'shiny'

The following object is masked from 'package:jsonlite':

    validate


Attaching package: 'shinyjs'

The following object is masked from 'package:shiny':

    runExample

The following objects are masked from 'package:methods':

    removeClass, show


Attaching package: 'DT'

The following objects are masked from 'package:shiny':

    dataTableOutput, renderDataTable


Listening on http://127.0.0.1:4292

```

If I close browser and press on **appname.bat** it does not launch again. I am not able to delete _error.log_ it says: _The action can't be completed because the file is open in Windows Command Processor_ .

I would very much appreciate any help/guidance.

**Comment by ivonavoroneckaja** [comment]
This issue has been solved here : http://stackoverflow.com/questions/37698454/r-shiny-desktopdeployr-stop-logging-error

**Comment by wleepang** [comment]
The log that is created helps for debugging if your app throws errors.
Regarding your closing issue, you still need to add a
`session$onSessionEnded` callback that calls `shiny::stopApp()` to your
shiny server code for the Rscript process to terminate correctly and
release the lock on the log file.

**Comment by ivonavoroneckaja** [comment]
Thank you, I have done it, just forgot to mention in the comment.
