### ISSUE TITLE
could the logo be changed?

### ISSUE THREAD

**Issue by zhangjunjiang** [wleepang/DesktopDeployR#30]
can we change the logo picture  of our app to a self_defined picture?

**Comment by wleepang** [comment]
For shiny webapps you can set a favicon.
See: https://stackoverflow.com/questions/30096187/favicon-in-shiny

**Comment by zhangjunjiang** [comment]
> For shiny webapps you can set a favicon.
> See: https://stackoverflow.com/questions/30096187/favicon-in-shiny
@wleepang 
thank you for your suggestion
I  want to change the logo of the batch file,not on the web page. 
Do you have any suggestion about this?

**Comment by Ljupch0** [comment]
You can create a shortcut to the batch file, then change the icon of the shortcut (properties > change icon).

**Comment by zhangjunjiang** [comment]
> You can create a shortcut to the batch file, then change the icon of the shortcut (properties > change icon).

good idea 
thank you @Ljupch0
