### ISSUE TITLE
See the console for the app that's running

### ISSUE THREAD

**Issue by Ljupch0** [wleepang/DesktopDeployR#32]
Hi Lee, great package. Worked out of the box.

However now I'm facing an issue with one of my apps. Is there an easy way to see the console for the app that is running through the DesktopDeployR framework? Would be very helpful to debug.

**Comment by Ljupch0** [comment]
I see now that of course this is the function of the error logs. However they are not generating :/

**Comment by wleepang** [comment]
Logs capture any output sent to stdout and stderr. There was a recent fix for R 4.0.x for logging. Make sure you have the most up to date `dist`.

**Comment by Ljupch0** [comment]
One way I got the console is by using `shinyShortcut` to create another bat file in the app folder. I think launching the app with this bat uses the standard R installation and library, but it will show you the console as the app is running. Usually the bugs I get with DesktopDeployR are of my own making: I forget to include files from the original directory that the app depends on.
