### ISSUE TITLE
Closing and Opening 

### ISSUE THREAD

**Issue by Dripdrop12** [wleepang/DesktopDeployR#5]
I've noticed that the shortcut does not work the second time I click it, but, if I go into the task manager and manually close the R-portable or just try to revisit the localhost address, then it works.

My server has:

shinyServer(function(input, output, session){
                session$onSessionEnded(function() {
                        stopApp()
                        q("no")
                })
        })

It just seems like R does not fully shutdown or chrome does not properly open the second time around.

**Comment by wleepang** [comment]
Are there any errors logged? Does this only happen with Chrome?

**Comment by Dripdrop12** [comment]
It was happening with Chrome, and there weren't any errors in the log.  I
restarted my computer and packaged the executable again and the bug
disappeared!

Thank you for following up so quickly.

What do you think about including an .iss file for Inno Setup or another
installation wizard?  I think that might really polish this repo off ;)

On Fri, Jun 10, 2016 at 1:40 AM, W. Lee Pang, PhD <notifications@github.com>
wrote:

> Are there any errors logged? Does this only happen with Chrome?
>
> On Wed, Jun 8, 2016, 10:25 PM Jonathan Hill <notifications@github.com>
> wrote:
>
> > I've noticed that the shortcut does not work the second time I click it,
> > but, if I go into the task manager and manually close the R-portable or
> > just try to revisit the localhost address, then it works.
> >
> > My server has:
> >
> > shinyServer(function(input, output, session){
> > session$onSessionEnded(function() {
> > stopApp()
> > q("no")
> > })
> > })
> >
> > It just seems like R does not fully shutdown or chrome does not open
> > properly the second time around.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/wleepang/DesktopDeployR/issues/5>, or mute the
> thread
> > <
> https://github.com/notifications/unsubscribe/AAWEZkHwQzQxnTwkRRBhgWhbZXpECmazks5qJ6PIgaJpZM4Ixo9l
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wleepang/DesktopDeployR/issues/5#issuecomment-225097991>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ88-HRay1kOwqUyBmzgVqf6oCS5xlf2ks5qKPiwgaJpZM4Ixo9l>
> .
>



-- 
Jonathan Hill, MPA
Cornell Institute for Public Affairs
Union College
Email: jmh558@cornell.edu
Phone: 585-967-5007

**Comment by wleepang** [comment]
@Dripdrop12 Adding a `*.iss` template file is a great idea!
