### ISSUE TITLE
Opening gWidgets2 Desktop App

### ISSUE THREAD

**Issue by jojop2** [wleepang/DesktopDeployR#6]
Hello,

thanks for your work.

My question is, if it is possible to use your solution to open an gWidgets2 (tcltk) App?
I tried and can see the Desktop App for half a second, but then it closes again by itself with the last log message: "Application terminated normally"

Thank you for any hint.

**Comment by wleepang** [comment]
Do you have a top level window dispose/close anywhere in your app (aside from a close button callback)?

**Comment by wleepang** [comment]
Closing as this is more than 1yr old. Feel free to reopen if still an issue.
